### ISSUE TITLE
Launcher example panics on search after selecting an app with keyboard.

### ISSUE THREAD

**Issue by edfloreshz** [pop-os/libcosmic#10]
Upon launch, if the user selects any entry in the launcher and then return to search something else, the program panics.

```
thread 'main' panicked at 'attempt to add with overflow', examples/launcher/window/mod.rs:143:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by leviport** [comment]
I was mistaken, moving back to libcosmic

**Comment by wash2** [comment]
Thanks for filing an issue! The gtk4 launcher is still very much a work in progress but I'll take a look tomorrow.

**Comment by edfloreshz** [comment]
I'm aware 🙂 I'll send PRs whenever I can.

**Comment by edfloreshz** [comment]
I can confirm that the panic is no longer present 👍🏼
