### ISSUE TITLE
Clipboard custom mime types

### ISSUE THREAD

**Issue by jackpot51** [pop-os/libcosmic#259]
We will need to support setting custom mime types for clipboard items

**Comment by WhyNotHugo** [comment]
Some very relevant notes that I left for `iced` on this topic some time ago: https://github.com/iced-rs/iced/discussions/1455

**Comment by WhyNotHugo** [comment]
Where is this implemented? I see clipboard support in github.com/pop-os/window_clipboard, but it only supports `String` (e.g.: utf-8 text). Am I looking in the wrong place?
