### ISSUE TITLE
No option to set windows icon

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/libcosmic#284]
I'm wondering why windows settings from Iced are not available ?

For example, on Linux, to show an app icon on the dock, it is possible to use the icon field of https://docs.rs/iced/latest/iced/window/struct.Settings.html with Iced. But there is no such option on libcosmic.

**Comment by mmstick** [comment]
Yes, this property is not given because it has no effect on Linux. Applications get their icons from their desktop entry files.
