### ISSUE TITLE
Icons and some other surfaces not rendering (Disabling presentation on ... due to NV Optimus and Intel Mesa < v21.2)

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/libcosmic#285]
In COSMIC Text c61885f, I'm currently seeing most of the window fail to render, with the terminal output `[2024-01-29T16:06:22Z WARN  wgpu_hal::vulkan::instance] Disabling presentation on 'Intel(R) Graphics (RPL-S)' (id 0x5d5f5ae956b0) due to NV Optimus and Intel Mesa < v21.2`:

![screenshot-2024-01-29-16-06-43](https://github.com/pop-os/cosmic-edit/assets/7199422/bd300c51-475e-4253-a642-beebd165c496)

As you can see, most of COSMIC Terminal ff1ba5b is rendering, but the minimize/maximize/close icons are not. COSMIC Files 44960f5 is also failing to render any of its icons. I get similar terminal output when launching those apps from a terminal.

This is on a serw13 in Hybrid mode.

**Comment by mmstick** [comment]
Will be fixed by the iced rebase with the updated wgpu library.

**Comment by jacobgkau** [comment]
This has been fixed by a patched wgpu 0.18 that includes the [version check fix](868033d6754253bc51aa886f7308ac6f0fa080d7): https://github.com/pop-os/wgpu/tree/v0.18 

Presumably, we'll still want the iced rebase staged in https://github.com/pop-os/libcosmic/pull/287 to fix it without the patch?

**Comment by mmstick** [comment]
Yeah, the iced rebase should have the patches included by default, so it won't be necessary to override the crate.

**Comment by WatchMkr** [comment]
@jacobgkau is this fixed?
