### ISSUE TITLE
Allow further customization for HeaderBar widget.

### ISSUE THREAD

**Issue by edfloreshz** [pop-os/libcosmic#299]
Sometimes when the window has not enough width the `HeaderBar` widget will hide the central widget.

We could give users the option to position the central widget below the menu bar when the window reaches a certain width:

![image](https://github.com/pop-os/cosmic-files/assets/22224438/f99d62d5-2144-4dc5-a92b-21baab4e5f51)

We could also let them position the menu bar below to leave room for the central widget:

![image](https://github.com/pop-os/cosmic-files/assets/22224438/ce6dfa3c-eadf-4871-8fae-ac06cbeb7384)

Let me know what you think!

**Comment by mmstick** [comment]
Needs approval from @pop-os/ux for this behavior

**Comment by maria-komarova** [comment]
I'm not sure this is till the case. There shouldn't be any central widget for Files app or any other app I can think of at the moment. Whenever we design the app there is generally a guidance for resizing the app that is provided with the designs. It is usually based on the specific case but overall we collapse the menus to a dropdown, collapse search to an icon button that expands the search on top of other controls. So I'm not sure I see the use cases yet for stacking the central widget.

**Comment by edfloreshz** [comment]
I opened this because of a previous design of Files, but in the current version this is no longer the case.

If you don't see a use case for this feel free to close 👍🏼

**Comment by maria-komarova** [comment]
Got it, thanks for clarifying. Yes, the implementation came sooner than design with Files.
