### ISSUE TITLE
Inactive Window Header Design Change

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/libcosmic#331]
The background color of the header will no longer change color. The icons change to indicate inactive state.

Design - https://www.figma.com/file/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?node-id=12298%3A80459&mode=dev

**Comment by edfloreshz** [comment]
@wash2 #338 should've closed this, should I close it?

**Comment by wash2** [comment]
Thanks for the reminder :)
