### ISSUE TITLE
Certain theme colors are inconsistent/don't exist across devices (divider colors specifically)

### ISSUE THREAD

**Issue by ryanabx** [pop-os/libcosmic#370]
I noticed while working on https://github.com/pop-os/cosmic-applets/pull/317 that the dividers don't have a noticeable color on my amd laptop

This is my device with an intel i5 8250u:
![screenshot-2024-04-01-03-05-48](https://github.com/pop-os/libcosmic/assets/56272643/cff5d53d-d290-4e01-9272-dea23cf551c5)

This is my device with an amd r9 6900hs and an amd radeon rx 6700s dGPU:
![screenshot-2024-04-01-03-04-28](https://github.com/pop-os/libcosmic/assets/56272643/3a8d061f-c2c2-44eb-8186-eb9e6a4a6088)

**Comment by git-f0x** [comment]
I did notice that the dividers disappeared at one point for me, but wasn't sure if it was intended (AMD graphics; and very old Intel graphics (might be software rendering)).

**Comment by edfloreshz** [comment]
I can reproduce this on 2 AMD machines.

**Comment by ryanabx** [comment]
> I did notice that the dividers disappeared at one point for me, but wasn't sure if it was intended (AMD graphics; and very old Intel graphics on a different system (might be software rendering for the latter)).

Cosmic-comp iirc doesn't support software rendering yet

**Comment by git-f0x** [comment]
That system doesn't support Vulkan or OpenGL 3, and I'm not sure if OpenGL 2 is supported by cosmic-comp (cosmic-term uses tiny-skia on that system), but idk.

**Comment by Drakulix** [comment]
> That system doesn't support Vulkan or OpenGL 3, and I'm not sure if OpenGL 2 is supported by cosmic-comp (cosmic-term uses tiny-skia on that system), but idk. Not that it matters much on such an old system.

Cosmic-comp can use OpenGL ES 2.0, if it has to.

**Comment by ryanabx** [comment]
I have some old screenshots from February showing that the colors were correct back then

**Comment by WatchMkr** [comment]
Perhaps related: pop-up outlines do not render correctly on some GPUs.

![Image](https://github.com/pop-os/libcosmic/assets/3430283/038f50be-4c99-4bef-956c-82c3df0160b1)

**Comment by ryanabx** [comment]
Looks like the colors are present, they just match the background color:

![screenshot-2024-04-16-05-38-58](https://github.com/pop-os/libcosmic/assets/56272643/eb877120-4089-40f5-a05c-95e656fea151)

Given that this is GPU dependent, I suppose it's supposed to be rendering a different color, and the color is probably correct in-code?

**Comment by git-f0x** [comment]
I don't believe this was the case before, but the dividers are now visible for me on Light theme in applets and Store.

**Comment by ryanabx** [comment]
That's not the case for me, but I'll see if it is after building for today.

**Comment by jackpot51** [comment]
We had a bug with theme derivation causing dividers to take on the background color. That is fixed but you must change the theme in an up to date settings app before it will take effect.

**Comment by git-f0x** [comment]
Oh, now that I changed "Application or window background" in Dark theme it seems to be fully fixed on my end.
And now I see that every 3rd and 6th window in the multiple window popup slightly clips outside the border (don't know beyond 6 since overflow isn't implemented).
![screenshot-2024-04-19-19-39-32](https://github.com/pop-os/libcosmic/assets/150025636/948837a4-d6be-4cc2-a14c-b82e44e178d1)

**Comment by ryanabx** [comment]
The colors are fixed for me too! Closing this issue
