### ISSUE TITLE
Design demo does not compile due to recent api changes.

### ISSUE THREAD

**Issue by leb-kuchen** [pop-os/libcosmic#374]

**Comment by juhp** [comment]
I just tried `just run cosmic` and it worked for me.

Does that replace cosmic-design-demo?

**Comment by juhp** [comment]
Ah nvm seems the opposite...

**Comment by juhp** [comment]
Anyway my reason for "coming here" is that `just run cosmic-design-demo` does not work currently, so probably not the best example :)

**Comment by mmstick** [comment]
The project is not maintained right now. It should be removed.

**Comment by MichaelMcDonnell** [comment]
I think this bug can be closed? I removed the design-demo example.
