### ISSUE TITLE
Cosmic applications no longer following cosmic set colorscheme

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/libcosmic#416]
Cosmic applications after a certain point in time no longer follow colorscheme set by cosmic-settings

Cosmic-term was likely broken by f720e63 (last good is https://github.com/pop-os/cosmic-term/commit/3ccfa4509d0f3bb2e9f133b9f394876728084a98 commits between don't compile)

cosmic-settings was broken I believe by https://github.com/pop-os/cosmic-settings/commit/2975318137b28303f85dd9542c6e7fb0ab79f4a1

cosmic-files I by https://github.com/pop-os/cosmic-files/commit/37a6f37f7f1ab51596d72de570e8ec2145397dd1

Im not sure if I need to bisect libcosmic itself but can if needed

**Comment by git-f0x** [comment]
They follow the configured color scheme for me. Have you tried changing some settings (e.g. Application or window background), since the changes might require resetting the theme?

**Comment by mmstick** [comment]
The theme config changed, so you need to recreate the theme. Likewise, applications need to update to the latest version of libcosmic to sync back with the latest theme changes

**Comment by Quackdoc** [comment]
Ah yeah that was it. I'll go ahead and close this.
