### ISSUE TITLE
Text inputs cause unresponsiveness

### ISSUE THREAD

**Issue by edfloreshz** [pop-os/libcosmic#417]
Copying and pasting into text fields results in unresponsiveness of any COSMIC application, I tested this with cosmic-tasks and cosmic-files so far.

## Steps to reproduce
1. Select a text field.
1. Copy or paste anything.

**Comment by joshuamegnauth54** [comment]
[Related issue](https://github.com/pop-os/cosmic-files/issues/138) in `cosmic-files`.
