### ISSUE TITLE
App Headers - Match inactive window design

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/libcosmic#450]
Current inactive window
![image](https://github.com/pop-os/libcosmic/assets/3430283/70f6e75a-90d2-47fb-89ff-e4f0782ded2c)

Design
![image](https://github.com/pop-os/libcosmic/assets/3430283/626c8067-d6c2-4c06-8b23-3715ce921efd)

The icons and menu (File, Edit, View) should be @on_bg_color at 75% opacity. The same applies to light mode.

**Comment by WatchMkr** [comment]
An expanded search icon should also use @on_bg_color at 75% 

![image](https://github.com/pop-os/libcosmic/assets/3430283/9f3fa106-c1db-4d27-97ed-f9757d1139c3)
(from settings or store)

**Comment by mmstick** [comment]
This was implemented by 9292ea647b42787cd8b219e50026ac4bdb00d716
