### ISSUE TITLE
Color picker selector disappears after choosing a color

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/libcosmic#488]
Use the color picker in Appearance. The selection circle disappears after choosing a color but should remain in the chosen color location.

**Comment by git-f0x** [comment]
For me the selection circle is only visible at the edges of the rectangle (it's placed below the color rectangle). It think it started happening when wgpu was enabled in COSMIC Settings (along with the roundness setting previews not displaying properly in dark theme).
