### ISSUE TITLE
Unexpected disable of nvidia vulkan

### ISSUE THREAD

**Issue by flukejones** [pop-os/libcosmic#490]
I was trying to work out what in the hell was setting `VK_LOADER_DRIVERS_DISABLE` to ignore nvidia...

```
./.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/f66544561aa0/iced/wgpu/src/window/compositor.rs
44:            std::env::set_var("VK_LOADER_DRIVERS_DISABLE", "nvidia*");
```

For the love of Cthulhu please don't do random stuff like this...

**Comment by flukejones** [comment]
I spent a literal hour trying to debug this, resulting in kernel changes and driver changes. Only to find the issue eventually with:

```
❯ vulkaninfo |grep GPU
WARNING: [Loader Message] Code 0 : loader_add_layer_properties: 'layers' tag not supported until file version 1.0.1, but /usr/share/vulkan/implicit_layer.d/nvidia_layers.json is reporting version 1
WARNING: [Loader Message] Code 0 : Driver "nvidia_icd.json" ignored because it was disabled by env var 'VK_LOADER_DRIVERS_DISABLE'
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
```

**Comment by mmstick** [comment]
This is to prevent the NVIDIA dGPU from waking up when Vulkan devices are being enumerated by vulkan-loader. NVIDIA will only be enabled when it is requested by the DE.

**Comment by flukejones** [comment]
@mmstick this breaks *everything else*. Including vkcube, steam, anything wanting vulkan that isn't cosmic.

**Comment by mmstick** [comment]
Sounds like something should be unsetting the variable after the applet is loaded.

**Comment by mmstick** [comment]
The egl-wayland fix doesn't apply to applications that use Vulkan, which are all of the libcosmic applications. We had to update libvulkan1 to get the ability to disable the NVIDIA GPU when enumerating vulkan devices with the vulkan-loader.

**Comment by mmstick** [comment]
Also, we do need to do this to prevent hybrid GPU systems from having a multi-second delay when opening an application. The application will stall until the NVIDIA dGPU wakes up, and then go back to sleep.

**Comment by mmstick** [comment]
I'll push libcosmic to the app list, library, and launcher once this is merged.

**Comment by mmstick** [comment]
The applets which launch applications are updated now.

**Comment by flukejones** [comment]
There seems to be some other stuff also using libcosmic which is still setting `VK_LOADER_DRIVERS_DISABLE` and not doing the unset unfortunately.

**Comment by flukejones** [comment]
Appears to be fixed with latest cosmic-epoch build (with all submodules updated via `git submodule foreach --recursive git pull`)
