### ISSUE TITLE
no crossplatform support

### ISSUE THREAD

**Issue by Doublonmousse** [pop-os/libcosmic#505]
Follow up of https://github.com/edfloreshz/cosmic-app-template/issues/7

Basically, the https://github.com/edfloreshz/cosmic-app-template demo won't compile on either windows or linux with traits bound not satisfied errors on windows and import errors on mac os.

Trying to make the examples of this repo compile on windows won't work either (will fail because it can't find wayland dependencies).

Iced does run just fine on windows so this is a libcosmic specific issue (cross platform support doesn't work on the later whereas it works with the original iced crate).

**Comment by wash2** [comment]
Ya, the first error does for sure seem related to DnD. Did https://github.com/pop-os/iced/pull/151 not fix the issue on macos?
