### ISSUE TITLE
Draw native window controls within the custom titlebar on non linux distributions

### ISSUE THREAD

**Issue by Doublonmousse** [pop-os/libcosmic#523]
I think that would result in a better experience for cross platform support, without removing anything from the custom titlebar.

On windows, this allows for the snap tool to work by hovering over the minimize or maximize button.

On Mac os, forcing the window controls to be on the right whilst all controls are on the left feels very weird.

**Comment by wiiznokes** [comment]
https://github.com/pop-os/libcosmic/commit/1e5828e01cfaffe99f1c3505083b1f590363a33e seems to have removed this feature, i'm not sure why

**Comment by mmstick** [comment]
@wiiznokes No point bundling icons that are already in the icon theme. Regardless, that never allowed using different icons. Only the embedded cosmic icons.

**Comment by wiiznokes** [comment]
Yeah, but it would be nice to have a fallback, my app on windows have no icons now

**Comment by wiiznokes** [comment]
Maybe with a cfg

**Comment by Doublonmousse** [comment]
Sorry but I don't feel like this closes the issue.

The core issue is that having custom window control means that the UX is worse for a cross platform app compared to any other framework (other than gtk4 with the custom titlebar).

And I argue that it's better to leave the custom window control (on both windows and mac os) instead of using custom ones on all os and not putting in the work required to make the windows work like any other window either (which I feel like it will never be done as the focus will be on linux first).

On windows 
- does snap layout work ? No (see screenshot)
![56563646-0cb5-4488-bc0f-7b7454b339f1](https://github.com/user-attachments/assets/5e95f20d-50fc-4c60-812b-360d4930918d)
- can you close the windows if the mouse is in the top right corner ? Probably not (because of the round button hitbox. Correct me if I'm wrong on this. This is also something I dislike about the cosmic DE in general)

On mac os
- you have the controls on the opposite side. Doesn't feel "native" in any way
- the controls you normally have won't be here
![full-screen-400](https://github.com/user-attachments/assets/cbbd9ad9-675a-42e2-8640-6ed58349ab46)

Additional issues may also be here doing that like resizing difficulties (or different/harder to use) for different input methods when using the top bar.

This feels like a step backwards compared to iced, and makes me feel like libcosmic will be the next gtk4 : great for linux but with much worse support in general for windows and mac os (gtk4 has all of the mentioned issues when the custom titlebar is used and then some). 

I'm sorry but saying "oh no it's crossplatform cause iced is" isn't cutting it. Especially when the experience is worse than just using iced directly ...
