### ISSUE TITLE
Missing build dependency libxkbcommon-dev

### ISSUE THREAD

**Issue by Spoomer** [pop-os/libcosmic#549]
Hello there,

I was trying to build libcosmic but I ran into a build error: "smithay-client-toolkit" needs "xkbcommon". 
After some research, I could fix with installing the package "libxkbcommon-dev". 
I think in the build section of the readme should include this dependency.

If you want I can create a PR for this. :)

**Comment by mmstick** [comment]
Added as part of 2170a65c89

**Comment by luishugoooo** [comment]
I get a missing xkbcommon error on macOS

**Comment by mmstick** [comment]
@FantixX You need to install the headers for it.
