### ISSUE TITLE
Bug: On Windows, the window control icons are always black, even if the theme is set to dark mode

### ISSUE THREAD

**Issue by netraptor** [pop-os/libcosmic#559]
I've been trying to track this down on my own, but I'm having trouble tracking my way through libcosmic's header icon styling.

On Windows, the window control icons in the top right of the window are always black no matter what the theme is set to, which renders them almost impossible to see when the theme is set to dark mode.

Example using the official cosmic app template:
![libcosmic_window-controls_lightmode](https://github.com/user-attachments/assets/5a9eb77c-2048-4aa3-9ec3-6d4225f3d8ba)
![libcosmic_window-controls_darkmode](https://github.com/user-attachments/assets/a76c50e7-6c8d-4708-b6c4-ab7b8fc8046d)

**Comment by wiiznokes** [comment]
I think that on me (https://github.com/pop-os/libcosmic/pull/553/files)

You could probably fix it by adding `.symbolic(true)` here https://github.com/pop-os/libcosmic/blob/756f4b6ba69d11075eb0c34ea0fc837bd27ad63a/src/widget/header_bar.rs#L376

**Comment by wiiznokes** [comment]
That would be great!
