### ISSUE TITLE
Popover / Popup glitch after closing it via "away" click

### ISSUE THREAD

**Issue by CristianKerr** [pop-os/libcosmic#610]
Hi,
I copied your solution of the show-more popup menu (you have it in settings) and there is a glitch:
1. click the show-more button: popup opens
2. click away (anywhere else in the app): popup closes
3. click on the show-more button again: popup opens and closes right away

bonus: if I click on edit button, the button opens context drawer. When I close the drawer, the menu is still open - is this intended (or do I have to handle the closing myself)?

Here is an ilustrative image to show where I click.
![image](https://github.com/user-attachments/assets/cefd291c-47e9-4edf-9230-3c488e32d8dc)

Can I somehow add a code that happens on_close? Because I think it can be caused by it closing automatically, but not reseting my variable.

**Comment by mmstick** [comment]
There is an on_close method that you may want to use

**Comment by CristianKerr** [comment]
Aha, my bad, I didn't updated libcosmic in a while. Thought it will happen with build. Thanks for the help!
