### ISSUE TITLE
Comapct mode > header bar items missing padding

### ISSUE THREAD

**Issue by KoreshKrasa** [pop-os/libcosmic#620]
Buttons (window controls and sidebar toggle) in headerbar are missing padding in compact mode.
![screenshot-2024-09-27-08-04-07](https://github.com/user-attachments/assets/244a8d2b-6d54-4c27-ba2d-8400e2e3e072)
Also search fields missing top padding
![screenshot-2024-09-27-08-05-38](https://github.com/user-attachments/assets/2b76c80c-b61f-4ee2-a0f4-969d5601e9ea)
Compared to menubar highlight that has top padding
![screenshot-2024-09-27-08-04-16](https://github.com/user-attachments/assets/fa81a4cd-e6f4-46d2-a1c6-426ebbd9d216)

**Comment by WatchMkr** [comment]
@maria-komarova I'm sure about padding around the buttons. I think it's 2px (and it's supposed to be compact). Maybe those are as intended. Search input blends into the focused accent though.

![image](https://github.com/user-attachments/assets/68c80f19-cafc-4c37-9db7-1505a1f833e5)

**Comment by maria-komarova** [comment]
Headerbar in the design has fixed height so I'm not sure what is going on there with padding which makes it difficult for me to give any suggestions.
