### ISSUE TITLE
[ENHANCEMENT] Different Colors for Navigation Buttons to Indicate Availability

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/libcosmic#621]
The next and previous navigation buttons currently use the same color, which does not provide clear indication of navigation possibilities. Differentiating the colors of these buttons would improve user experience by indicating whether more items are available (in the Cosmic App Store while viewing images) or if directories have been previously opened (in Cosmic Files)

https://github.com/user-attachments/assets/d125adcc-fe8a-4964-85c7-e1d3e896bbb3

**Comment by jackpot51** [comment]
Moved to libcosmic, as the bug is that disabled style is not reflected in icon buttons.
