### ISSUE TITLE
libcosmic update for ContextDrawer header (back/forward/gallery)

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/libcosmic#625]

**Comment by WatchMkr** [comment]
Looking good in regular mode. This needs to be applied to dialog mode.

**Comment by git-f0x** [comment]
I think this just need a `cosmic-files` dependency update in apps. I've got PRs for Terminal and Text Editor that update dependencies, which make the buttons show in the context drawer header in the dialog.
I think Settings needs a dependency update in xdg-desktop-portal-cosmic, and there's an open PR there that updates them.

**Comment by git-f0x** [comment]
The updated dialog should now be used everywhere. This can probably be closed.
