### ISSUE TITLE
Toggler can't be in disabled state

### ISSUE THREAD

**Issue by bhh32** [pop-os/libcosmic#640]
A button is in a disabled state if you do not add the on_press() function when building it. I've used this quite a lot in a couple of projects I'm working on. However, I ran into a situation where I needed to do something similar with a toggler and cannot put the toggler in a disabled state. When creating the toggler the message (for the Fn Message parameter) is required, and so there is no way to put it in a disabled state if it's needed.

**Comment by wiiznokes** [comment]
This is implemented in upstream Iced + the api got better :) https://github.com/iced-rs/iced/blob/master/widget/src/toggler.rs

**Comment by git-f0x** [comment]
This can possibly be closed now, since libcosmic was rebased to latest iced.
