### ISSUE TITLE
Add comments to your commits

### ISSUE THREAD

**Issue by kleenleen** [pop-os/libcosmic#651]
I really love the COSMIC project and to follow its progress, but I find it very annoying the devs never take 1 minute to add a helpful comment (even a single liner) to describe their commits (what it changes, why it's done, ...at least).

The problem is not a few commits that are missing comments, it's that none of them have any comment!

Key in development, it to document and keep track of reasons for update, I think regarding this fact, you can improve the project by starting this good habit.

Best

**Comment by mmstick** [comment]
That's what the commit title message is for. We generally follow the Conventional Commit spec, so every commit is already self-explanatory. Additional descriptions are only added if the title isn't enough.
