### ISSUE TITLE
Feedback on About feature

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/libcosmic#696]
I find the api for about a bit odd. Imho it should be a widget. I don't understand why it is defined in the Application trait, since it's not something that libcosmic can position automatically. It would be more consistent to just call `widget::about(About {..})`. I don't really see an use case for overwridding `fn about()`.

@edfloreshz any thought ? i can work on it if its ok

**Comment by edfloreshz** [comment]
I think this is a good idea.

**Comment by edfloreshz** [comment]
If you don't mind I'd like to work on it 🙂

**Comment by wiiznokes** [comment]
I already started lol

**Comment by edfloreshz** [comment]
Oh, sorry 😰

**Comment by wiiznokes** [comment]
no worries, i was taking an impossible direction anyway i believe (started implementing `From<..> for Element>)`. 

Thanks for working on this
