### ISSUE TITLE
Dropdown broken in ContextDrawer

### ISSUE THREAD

**Issue by CristianKerr** [pop-os/libcosmic#713]
Hi,
dropdown currently do not show overlay in ContextDrawer. This has worked several weeks ago. 
I think it opens the overlay under the drawer because when I click the dropdown and then e.g. maximize window button, the first click does nothing (as if the overlay was closed by clicking away).
This may be related to #428 but I am sure that this worked a few weeks ago and the issue is from May.

**Comment by edfloreshz** [comment]
The dropdown is being rendered outside the main window for some reason, if you collapse the navigation bar the dropdown should display again.

**Comment by CristianKerr** [comment]
You are right, when I hide navigation I see the overlay. Weird is that popover added to a button works correctly (just a fyi)

**Comment by edfloreshz** [comment]
Yes, popovers appear to be working fine as far as I can tell.
