### ISSUE TITLE
Num pad do not work with input fields

### ISSUE THREAD

**Issue by CristianKerr** [pop-os/libcosmic#740]
Hi,
My num pad doesn't work with the input fields (e.g. text input). Trying to turn num pad off and on doesn't help. 
I use latest Fedora, so there might be some incompatibility with the system maybe?

Edit: just want to add that the keys behave always as their alternative functions like arrows, insert, pg up, pg down etc..

**Comment by git-f0x** [comment]
Same issue as #702.
