### ISSUE TITLE
App Library opens the the app when navigating with the keyboard.

### ISSUE THREAD

**Issue by edfloreshz** [pop-os/libcosmic#8]
When I run the `app_library` example and try to navigate the app grid, I encounter an issue where the second selected app automatically opens without tapping `ENTER`.

You can replicate this behavior by opening the App Library and tapping the down arrow twice in your keyboard.

**Comment by leviport** [comment]
Hm, I'm not seeing this on my Oryx Pro. Can you post some info about your machine and OS?

**Comment by edfloreshz** [comment]
I'm on the `prototype` branch and it happens too.

![ezgif-5-19169414b1](https://user-images.githubusercontent.com/22224438/149214293-bba3403f-b59f-4169-8322-75cdcb9c90a3.gif)

The sequence was Down, Down and it opened the app without typing ENTER.

Motherboard: Aorus X570 Pro Wifi
CPU: Ryzen 7 5800X
GPU: Radeon 5700 XT
RAM: 16 GB
OS: Pop!_OS 21.04
